class ForpyException(Exception): ...

class MainFileException(ForpyException): ...
class GlobalException(ForpyException): ...

class NoFileSpecified(MainFileException): ...

class NotImplemented(GlobalException): ...

